window
  .createMapImage(
    {
      version: 8,
      light: {
        anchor: "map",
        color: "rgba(255,255,255,1)",
        intensity: 0.5,
      },
      sprite: [
        {
          id: "arrows",
          url: "https://mapstudio.ai/icons/arrows",
        },
        {
          id: "points",
          url: "https://mapstudio.ai/icons/points-v2",
        },
      ],
      glyphs: "https://fonts.mapstudio.ai/font/{fontstack}/{range}",
      sources: {
        planet: {
          type: "vector",
          url: "https://tiles.mapstudio.ai/20250424.json",
          exportAttribution: "© OSM.org",
        },
        terrarium_land: {
          type: "raster-dem",
          tiles: [
            "https://terrain.mapstudio.ai/terrarium-land/{z}/{y}/{x}.png",
          ],
          minzoom: 0,
          maxzoom: 13,
          encoding: "terrarium",
          tileSize: 256,
        },
        features: {
          type: "geojson",
          data: {
            type: "FeatureCollection",
            features: [
              {
                id: "ppVJRs",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [13.4609744, 48.5748229],
                },
                properties: {
                  id: "ppVJRs",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Passau",
                    position: "bottom",
                  },
                },
              },
              {
                id: "WMS9wB",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [13.80866, 48.45927],
                },
                properties: {
                  id: "WMS9wB",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Wesenufer",
                    position: "bottom",
                  },
                },
              },
              {
                id: "q6JLzX",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [13.7325696, 48.5052032],
                },
                properties: {
                  id: "q6JLzX",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Engelhartszell",
                    position: "bottom",
                  },
                },
              },
              {
                id: "GtFXxD",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [14.4793948, 48.2141482],
                },
                properties: {
                  id: "GtFXxD",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Enns",
                    position: "bottom",
                  },
                },
              },
              {
                id: "u2as8w",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [15.1508476, 48.2142911],
                },
                properties: {
                  id: "u2as8w",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Marbach",
                    position: "bottom",
                  },
                },
              },
              {
                id: "-ku1ap",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [15.7441868, 48.3499106],
                },
                properties: {
                  id: "-ku1ap",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Traismauer",
                    position: "bottom",
                  },
                },
              },
              {
                id: "QLpLRv",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [16.3725042, 48.2083537],
                },
                properties: {
                  id: "QLpLRv",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 1,
                    },
                    size: 24,
                    color: "#D10A10",
                    image: "points:house",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Wien",
                    position: "bottom",
                  },
                },
              },
              {
                id: "UV4khj",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [13.4318, 48.4569975],
                },
                properties: {
                  id: "UV4khj",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 0,
                    },
                    size: 12,
                    color: "#D10A10",
                    image: "points:circle",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Schärding",
                  },
                },
              },
              {
                id: "bx8pGl",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [14.286198, 48.3059078],
                },
                properties: {
                  id: "bx8pGl",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 0,
                    },
                    size: 12,
                    color: "#D10A10",
                    image: "points:circle",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Linz",
                  },
                },
              },
              {
                id: "IyRUZt",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [15.1571646, 48.2252539],
                },
                properties: {
                  id: "IyRUZt",
                  type: "point",
                  hovering: false,
                  selected: false,
                  icon: {
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 0,
                    },
                    size: 12,
                    color: "#D10A10",
                    image: "points:circle",
                  },
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 14,
                    color: "#000000",
                    field: "Maria Taferl",
                    offset: 0,
                    position: "top",
                  },
                },
              },
              {
                id: "pxVfog",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [13.2, 48.65],
                },
                properties: {
                  id: "pxVfog",
                  type: "point",
                  hovering: false,
                  selected: false,
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 18,
                    color: "#777777",
                    field: "Deutschland",
                  },
                },
              },
              {
                id: "oy8U1h",
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [15.5, 48.1],
                },
                properties: {
                  id: "oy8U1h",
                  type: "point",
                  hovering: false,
                  selected: false,
                  text: {
                    font: {
                      family: "Open Sans",
                      variant: "Regular",
                    },
                    halo: {
                      blur: 0,
                      color: "#FFFFFF",
                      width: 2,
                    },
                    size: 18,
                    color: "#777777",
                    field: "Österreich",
                  },
                },
              },
            ],
          },
        },
        countries: {
          type: "vector",
          url: "https://tiles.mapstudio.ai/countries/20250208.json",
          exportAttribution: "© OSM.org",
        },
      },
      layers: [
        {
          id: "background",
          type: "background",
          paint: {
            "background-color": "rgba(236,236,236,1)",
          },
        },
        {
          id: "earth-earth-fill",
          type: "fill",
          source: "planet",
          "source-layer": "earth",
          metadata: {
            layerRef: "earth",
            settingsId: "earth-earth",
          },
          minzoom: 0,
          maxzoom: 24,
          paint: {
            "fill-color": "rgba(225,243,225,1)",
          },
        },
        {
          id: "landcover-5SqYT-Os-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-5SqYT-Os",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: ["==", ["get", "kind"], "forest"],
          paint: {
            "fill-color": "rgba(168,230,204,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landuse-rvIzayL7-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-rvIzayL7",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: [
            "in",
            ["get", "kind"],
            ["literal", ["forest", "wetland", "woods"]],
          ],
          paint: {
            "fill-color": "rgba(162,226,198,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landuse-zvG0ehww-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-zvG0ehww",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: [
            "in",
            ["get", "kind"],
            [
              "literal",
              [
                "cemetery",
                "garden",
                "zoo",
                "scrub",
                "dog_park",
                "park",
                "national_park",
              ],
            ],
          ],
          paint: {
            "fill-color": "rgba(187,236,217,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landcover-JkZa2S_H-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-JkZa2S_H",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: ["==", ["get", "kind"], "barren"],
          paint: {
            "fill-color": "rgba(250,246,231,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landuse-YpNz2GvF-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-YpNz2GvF",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: ["==", ["get", "kind"], "bare_rock"],
          paint: {
            "fill-color": "rgba(236,232,227,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landuse-Rd2sMsSa-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-Rd2sMsSa",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: [
            "in",
            ["get", "kind"],
            ["literal", ["beach", "sand", "camp_site"]],
          ],
          paint: {
            "fill-color": "rgba(252,244,214,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landcover-D6rzvC1P-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-D6rzvC1P",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: [
            "in",
            ["get", "kind"],
            ["literal", ["grassland", "farmland"]],
          ],
          paint: {
            "fill-color": "rgba(187,236,217,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landcover-XqVbeJ0G-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-XqVbeJ0G",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: ["==", ["get", "kind"], "scrub"],
          paint: {
            "fill-color": "rgba(232,248,228,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landcover-BtCWHDWS-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-BtCWHDWS",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: ["==", ["get", "kind"], "urban_area"],
          paint: {
            "fill-color": "rgba(236,235,229,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landcover-anwT36Rc-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landcover",
          metadata: {
            layerRef: "landcover",
            settingsId: "landcover-anwT36Rc",
          },
          minzoom: 0,
          maxzoom: 7,
          filter: ["==", ["get", "kind"], "glacier"],
          paint: {
            "fill-color": "rgba(255,255,255,1)",
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["zoom"],
              0,
              1,
              6,
              1,
              7,
              0,
            ],
          },
        },
        {
          id: "landuse-AjtkMP4a-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-AjtkMP4a",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: ["==", ["get", "kind"], "glacier"],
          paint: {
            "fill-color": "rgba(255,255,255,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landuse-R2WUs0xo-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-R2WUs0xo",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: [
            "in",
            ["get", "kind"],
            [
              "literal",
              [
                "industrial",
                "military",
                "grocery",
                "cafe",
                "commercial",
                "hotel",
                "aerodrome",
                "university",
                "railway",
                "runway",
                "taxiway",
              ],
            ],
          ],
          paint: {
            "fill-color": "rgba(224,224,211,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landuse-3RvD-52k-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-3RvD-52k",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: ["==", ["get", "kind"], "protected_area"],
          paint: {
            "fill-color": "rgba(187,236,217,0.6)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "landuse-lb7L9XMX-fill",
          type: "fill",
          source: "planet",
          "source-layer": "landuse",
          metadata: {
            layerRef: "landuse",
            settingsId: "landuse-lb7L9XMX",
          },
          minzoom: 6,
          maxzoom: 24,
          filter: [
            "in",
            ["get", "kind"],
            [
              "literal",
              [
                "attraction",
                "college",
                "footway",
                "university",
                "neighbourhood",
              ],
            ],
          ],
          paint: {
            "fill-color": "rgba(242,242,242,1)",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 7, 1],
          },
        },
        {
          id: "hillshade-earth_relief",
          type: "hillshade",
          source: "terrarium_land",
          metadata: {
            layerRef: "hillshade",
            settingsId: "hillshade-earth_relief",
          },
          minzoom: 0,
          maxzoom: 24,
          paint: {
            "hillshade-illumination-direction": 270,
            "hillshade-illumination-anchor": "map",
            "hillshade-shadow-color": "rgba(61,52,10,0.8)",
            "hillshade-highlight-color": "rgba(248,247,247,1)",
            "hillshade-accent-color": "rgba(83,82,82,0.4)",
            "hillshade-exaggeration": 0.7,
          },
        },
        {
          id: "water-water-fill",
          type: "fill",
          source: "planet",
          "source-layer": "water",
          metadata: {
            layerRef: "water",
            settingsId: "water-water",
          },
          minzoom: 0,
          maxzoom: 24,
          filter: ["==", ["geometry-type"], "Polygon"],
          paint: {
            "fill-color": "rgba(101,209,230,1)",
          },
        },
        {
          id: "boundaries-D2Q5H7U0",
          type: "line",
          source: "planet",
          "source-layer": "boundaries",
          metadata: {
            layerRef: "boundaries",
            settingsId: "boundaries-D2Q5H7U0",
          },
          minzoom: 0,
          maxzoom: 24,
          filter: [
            "all",
            ["!", ["has", "disputed"]],
            ["==", ["get", "kind"], "country"],
          ],
          layout: {
            "line-cap": "round",
            "line-join": "round",
          },
          paint: {
            "line-color": "rgba(0,0,0,0.5)",
            "line-width": 1,
            "line-dasharray": ["literal", [4, 4]],
          },
        },
        {
          id: "boundaries-mN6yCZyo",
          type: "line",
          source: "planet",
          "source-layer": "boundaries",
          metadata: {
            layerRef: "boundaries",
            settingsId: "boundaries-mN6yCZyo",
          },
          minzoom: 0,
          maxzoom: 24,
          filter: [
            "all",
            ["has", "disputed"],
            ["==", ["get", "kind"], "country"],
          ],
          layout: {
            "line-cap": "round",
            "line-join": "round",
          },
          paint: {
            "line-color": "rgba(0,0,0,0.5)",
            "line-width": 1,
            "line-dasharray": ["literal", [0.6, 4]],
          },
        },
        {
          id: "mapstudio-cut-country",
          type: "fill",
          source: "countries",
          "source-layer": "countries",
          paint: {
            "fill-color": "#8742F3",
            "fill-opacity": [
              "case",
              ["boolean", ["feature-state", "hover"], false],
              0.7,
              0,
            ],
            "fill-outline-color": "#8742F3",
          },
        },
        {
          id: "ppVJRs-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "ppVJRs"],
          layout: {
            "text-field": "Passau",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "ppVJRs-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "ppVJRs"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "ppVJRs-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "ppVJRs"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "WMS9wB-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "WMS9wB"],
          layout: {
            "text-field": "Wesenufer",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "WMS9wB-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "WMS9wB"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "WMS9wB-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "WMS9wB"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "q6JLzX-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "q6JLzX"],
          layout: {
            "text-field": "Engelhartszell",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "q6JLzX-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "q6JLzX"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "q6JLzX-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "q6JLzX"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "GtFXxD-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "GtFXxD"],
          layout: {
            "text-field": "Enns",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "GtFXxD-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "GtFXxD"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "GtFXxD-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "GtFXxD"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "u2as8w-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "u2as8w"],
          layout: {
            "text-field": "Marbach",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "u2as8w-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "u2as8w"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "u2as8w-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "u2as8w"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "-ku1ap-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "-ku1ap"],
          layout: {
            "text-field": "Traismauer",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "-ku1ap-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "-ku1ap"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "-ku1ap-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "-ku1ap"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "QLpLRv-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "QLpLRv"],
          layout: {
            "text-field": "Wien",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.890625],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "QLpLRv-icon",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "QLpLRv"],
          layout: {
            "icon-image": "points:house",
            "icon-size": 0.34285714285714286,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": false,
            "icon-ignore-placement": false,
          },
          paint: {
            "icon-color": "#D10A10",
            "icon-halo-color": "#FFFFFF",
            "icon-halo-width": 1,
          },
        },
        {
          id: "QLpLRv-icon-selected",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "QLpLRv"],
          layout: {
            "icon-image": "selected-rect",
            "icon-size": 0.7272727272727273,
            "icon-anchor": "center",
            "icon-pitch-alignment": "viewport",
            "icon-rotation-alignment": "viewport",
          },
          paint: {
            "icon-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
          },
        },
        {
          id: "UV4khj-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "UV4khj"],
          layout: {
            "text-field": "Schärding",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.514051220350636],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "UV4khj-icon",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "UV4khj"],
          paint: {
            "circle-color": "#D10A10",
            "circle-radius": 4.5,
            "circle-stroke-color": "#FFFFFF",
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "UV4khj-icon-selected",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "UV4khj"],
          paint: {
            "circle-opacity": 0,
            "circle-radius": 4.5,
            "circle-stroke-color": "#6D28D9",
            "circle-stroke-width": 1,
            "circle-stroke-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "bx8pGl-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "bx8pGl"],
          layout: {
            "text-field": "Linz",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "top",
            "text-offset": [0, 0.514051220350636],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "bx8pGl-icon",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "bx8pGl"],
          paint: {
            "circle-color": "#D10A10",
            "circle-radius": 4.5,
            "circle-stroke-color": "#FFFFFF",
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "bx8pGl-icon-selected",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "bx8pGl"],
          paint: {
            "circle-opacity": 0,
            "circle-radius": 4.5,
            "circle-stroke-color": "#6D28D9",
            "circle-stroke-width": 1,
            "circle-stroke-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "IyRUZt-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "IyRUZt"],
          layout: {
            "text-field": "Maria Taferl",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 14,
            "text-anchor": "bottom",
            "text-offset": [0, -0.514051220350636],
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#000000",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "IyRUZt-icon",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "IyRUZt"],
          paint: {
            "circle-color": "#D10A10",
            "circle-radius": 4.5,
            "circle-stroke-color": "#FFFFFF",
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "IyRUZt-icon-selected",
          type: "circle",
          source: "features",
          filter: ["==", ["get", "id"], "IyRUZt"],
          paint: {
            "circle-opacity": 0,
            "circle-radius": 4.5,
            "circle-stroke-color": "#6D28D9",
            "circle-stroke-width": 1,
            "circle-stroke-opacity": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              1,
              0,
            ],
            "circle-pitch-alignment": "viewport",
          },
        },
        {
          id: "pxVfog-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "pxVfog"],
          layout: {
            "text-field": "Deutschland",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 18,
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#777777",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
        {
          id: "oy8U1h-text",
          type: "symbol",
          source: "features",
          filter: ["==", ["get", "id"], "oy8U1h"],
          layout: {
            "text-field": "Österreich",
            "text-font": ["literal", ["Open Sans Regular"]],
            "text-size": 18,
            "text-pitch-alignment": "viewport",
            "text-allow-overlap": true,
            "icon-allow-overlap": true,
            "text-ignore-placement": true,
            "icon-ignore-placement": true,
            "icon-text-fit": "both",
            "icon-image": [
              "case",
              [
                "any",
                ["==", ["get", "selected"], true],
                ["==", ["get", "hovering"], true],
              ],
              "selected-rect",
              "none",
            ],
            "icon-rotate": 0,
            "icon-pitch-alignment": "viewport",
          },
          paint: {
            "text-color": "#777777",
            "text-halo-color": "#FFFFFF",
            "text-halo-width": 2,
          },
        },
      ],
    },
    {
      center: [14.833230505105803, 48.232945619175524],
      zoom: 7.413052347276693,
    },
    {
      width: 1000,
      height: 1000,
      pixelRatio: 2,
      timeoutMs: 30000,
      format: "png",
    },
  )
  .then((dataUrl) => {
    // Create a container to display the map image
    const imageContainer = document.createElement("div");
    imageContainer.style.width = "100%";
    imageContainer.style.maxWidth = "1000px";
    imageContainer.style.margin = "20px auto";
    imageContainer.style.border = "1px solid #ccc";
    imageContainer.style.borderRadius = "4px";
    imageContainer.style.overflow = "hidden";

    // Create the image element
    const mapImage = document.createElement("img");
    mapImage.src = dataUrl;
    mapImage.style.width = "100%";
    mapImage.style.display = "block";

    // Add the image to the container
    imageContainer.appendChild(mapImage);

    // Add the container to the document body
    document.body.appendChild(imageContainer);

    console.log("Map image has been displayed in the container");
  });
